version: '3'

services:
  checkout_api:
    image: node
    ports:
      - 8083:8083
    environment: 
      - PACT_BROKER_URL=http://192.168.48.1:8073
    volumes: 
      - .:/src
    working_dir: /src
    command: tail -f /dev/null